---
repos:
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.20.0
      hooks:
          - id: commitizen
            stages: [commit-msg]
    - repo: https://github.com/ambv/black
      rev: 21.11b1
      hooks:
          - id: black
